// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class CssSelector {
    private WebDriver driver;
    private final String BASE_URL = "http://localhost/tiklabana.php";


    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver.exe");
        driver = new ChromeDriver();

    }

    @Test
    public void test() {
        driver.get(BASE_URL);
        driver.findElement(By.cssSelector("div.container button")).click();
    }


    @After
    public void tearDown() {
        //driver.quit();
    }

}
