// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class LastTutorial {
    WebDriver driver;
    private final String BASE_URL = "http://localhost/kayit.php/";

    @Before
    public void setUp(){
        System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver.exe");
        driver = new ChromeDriver();
    }

    @Test
    public void test(){
        driver.get(BASE_URL);
        driver.findElement(By.name("email")).sendKeys("mervealgi@gmail.com");
        driver.findElement(By.name("name")).sendKeys("Merve");
        driver.findElement(By.name("surname")).sendKeys("Algı");
        driver.findElement(By.name("password")).sendKeys("1234");
        driver.findElement(By.name("password-repeat")).sendKeys("1234");
        driver.findElement(By.tagName("button")).click();
    }

    @After
    public void tearDown(){
     }
}