// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class xpath {
    WebDriver driver;
    private final String BASE_URL = "http://localhost/kayit.php/";

    @Before
    public void setUp(){
        System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver.exe");
        driver = new ChromeDriver();
    }

    @Test
    public void test(){
        driver.get(BASE_URL);
        driver.findElement(By.xpath("/html/body/div/div/form/div[1]/input")).sendKeys("mervealgi@gmail.com");
        driver.findElement(By.xpath("/html/body/div/div/form/div[2]/input")).sendKeys("Merve");
        driver.findElement(By.xpath("/html/body/div/div/form/div[3]/input")).sendKeys("Algı");
        driver.findElement(By.xpath("/html/body/div/div/form/div[4]/input")).sendKeys("12345");
        driver.findElement(By.xpath("/html/body/div/div/form/div[5]/input")).sendKeys("12345");
        driver.findElement(By.xpath("/html/body/div/div/form/div[2]/input"))
    }

    @After
    public void tearDown(){

    }
}